routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@getIndex');
Route::get('/corres', 'PagesController@getCorres');

Route::resource('voluntarios','VoluntarioController');

Route::resource('lancamentos','LancamentoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/_footer.blade.php
<br>
<br>
<br>
<p class="text-center">Copyright LBM - Todos os direitos reservados</p>

resources/views/partials/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>SPC @yield('title')</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

{{ Html::style('css/bootstrap-table.css') }}
{{ Html::style('css/bootstrap-table-filter-control.css') }}
{{ Html::style('css/styles.css') }}

@yield('css')

resources/views/partials/_messages.blade.php
@if (Session::has('success'))

	<div class="alert alert-success" role="alert">
		<strong>Sucesso:</strong> {{ Session::get('success') }}
	</div>

@endif

@if (count($errors) > 0)

	<div class="alert alert-danger" role="alert">
		<strong>Erros:</strong> 
		<ul>
			@foreach ($errors->all() as $e)
				<li>{{ $e }}</li>
			@endforeach			
		</ul>
	</div>

@endif

resources/views/partials/_navbar.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url('/') }}">SPC</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {{-- <ul class="nav navbar-nav">
        <li class="{{ Request::is('/') ? 'active' : '' }}"><a href="/">Águas</a></li>
        <li class="{{ Request::is('corres') ? 'active' : '' }}"><a href="/corres">Corres</a></li>
      </ul> --}}
      <ul class="nav navbar-nav navbar-right">
        @guest
            <li><a href="{{ route('login') }}">Login</a></li>
        @else
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            {{ Auth::user()->name }} <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{{ route('lancamentos.index') }}">Lançamentos</a></li>
              <li><a href="{{ route('voluntarios.index') }}">Voluntários</a></li>
              <li><a href="{{ route('register') }}">Registrar Usuário</a></li>
              <li role="separator" class="divider"></li>
              <li>
                <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                             document.getElementById('logout-form').submit();">
                    Sair
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
              </li>
            </ul>
          </li>
        @endguest
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

resources/views/partials/_scripts.blade.php
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- DataTables -->
{{ Html::script('datatables.net/js/jquery.dataTables.min.js')}}
{{ Html::script('datatables.net-bs/js/dataTables.bootstrap.min.js')}}

{{ Html::script('js/bootstrap-table.js') }}
{{ Html::script('js/bootstrap-table-filter-control.js') }}
{{ Html::script('inputmask/dist/jquery.mask.min.js') }}

@yield('js')